language: python
dist: xenial
cache: false
env:
  global:
    - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
    - SEGFAULT_SIGNALS=all
matrix:
  include:
    - python: '3.6'
      env:
        - TOXENV=check
    - python: '3.6'
      env:
        - TOXENV=docs
    - env:
        - TOXENV=py27-cover,codecov,coveralls
      python: '2.7'
    - env:
        - TOXENV=py27-nocov
      python: '2.7'
    - env:
        - TOXENV=py34-cover,codecov,coveralls
      python: '3.4'
    - env:
        - TOXENV=py34-nocov
      python: '3.4'
    - env:
        - TOXENV=py35-cover,codecov,coveralls
      python: '3.5'
    - env:
        - TOXENV=py35-nocov
      python: '3.5'
    - env:
        - TOXENV=py36-cover,codecov,coveralls
      python: '3.6'
    - env:
        - TOXENV=py36-nocov
      python: '3.6'
    - env:
        - TOXENV=py37-cover,codecov,coveralls
      python: '3.7'
    - env:
        - TOXENV=py37-nocov
      python: '3.7'
    - env:
        - TOXENV=pypy-cover,codecov,coveralls
      python: 'pypy'
    - env:
        - TOXENV=pypy-nocov
      python: 'pypy'
    - env:
        - TOXENV=pypy3-cover,codecov,coveralls
        - TOXPYTHON=pypy3
      python: 'pypy3'
    - env:
        - TOXENV=pypy3-nocov
        - TOXPYTHON=pypy3
      python: 'pypy3'
before_install:
  - python --version
  - uname -a
  - lsb_release -a || true
install:
  - python -mpip install --progress-bar=off tox -rci/requirements.txt
  - virtualenv --version
  - easy_install --version
  - pip --version
  - tox --version
script:
  - tox -v
after_failure:
  - more .tox/log/* | cat
  - more .tox/*/log/* | cat
notifications:
  email:
    on_success: never
    on_failure: always
